
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 17 02:34:17 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MONKEY = 49;
  public static final int CONST = 16;
  public static final int NAMESPACE = 3;
  public static final int READ_ = 4;
  public static final int HASH = 51;
  public static final int SEMI = 40;
  public static final int GREATER = 35;
  public static final int LPAREN = 20;
  public static final int CONTINUE = 13;
  public static final int LESS = 34;
  public static final int FOR = 14;
  public static final int MINUS = 26;
  public static final int STAT = 15;
  public static final int GREQ = 36;
  public static final int RPAREN = 21;
  public static final int AND = 29;
  public static final int NSAME = 38;
  public static final int OR = 30;
  public static final int COMMA = 41;
  public static final int CLASS = 11;
  public static final int INC = 32;
  public static final int DIV = 28;
  public static final int PLUS = 25;
  public static final int IF = 8;
  public static final int LSQBRACE = 22;
  public static final int DOT = 43;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int EQUAL = 24;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 27;
  public static final int NUMBER = 47;
  public static final int MOD = 31;
  public static final int IDENT = 48;
  public static final int VOID = 7;
  public static final int NEW_ = 12;
  public static final int BOOL_VALUE = 45;
  public static final int ARROW = 42;
  public static final int COLON = 44;
  public static final int SAME = 39;
  public static final int LBRACE = 18;
  public static final int ELSE = 9;
  public static final int GOTO = 50;
  public static final int CHAR_VALUE = 46;
  public static final int RBRACE = 19;
  public static final int EXTENDS = 17;
  public static final int LEQ = 37;
  public static final int RSQBRACE = 23;
  public static final int DEC = 33;
  public static final int BREAK_ = 10;
  public static final int PRINT = 5;
}

